Library/Controllers/MenuItemController.cs
using Library.DAL;
using Library.DAL.Repositories;
using Library.Domain.Entity;
using Library.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class MenuItemController : Controller
    {
        private readonly IMenuItemRepository _repository;
        public MenuItemController(IMenuItemRepository repository)
        {
            _repository = repository;
        }
        public async Task<IActionResult> Index()
        {
            var menuItem = await _repository.GetAllMenuItems();
            return View(menuItem);
        }
        public IActionResult Details(int id)
        {
            var menuItem =_repository.GetMenuItemById(id);
            if(menuItem == null)
            {
                return NotFound();
            }
            return View(menuItem);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(MenuItem menuItem)
        {
            if(ModelState.IsValid)
            {
                _repository.AddMenuItem(menuItem);
                return RedirectToAction("Index");
            }
            return View(menuItem);
        }
        public IActionResult Edit(int id)
        {
            var menuItem = _repository.GetMenuItemById(id);
            if(menuItem == null)
            {
                return NotFound();
            }
            return View(menuItem);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(MenuItem menuItem)
        {
            if(ModelState.IsValid)
            {
                _repository.UpdateMenuItem(menuItem);
                return RedirectToAction("Index");
            }
            menuItem.ModifiedAt = DateTime.Now;
            return View(menuItem);
        }
        public IActionResult Delete(int id)
        {
            var menuItem = _repository.GetMenuItemById(id);
            if( menuItem == null)
            {
                return NotFound();
            }
            return View(menuItem);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(MenuItem menuItem)
        {
            _repository.DeleteMenuItem(menuItem);
            return RedirectToAction("Index");
        }
    }
}

Library/Views/MenuItem/Create.cshtml
@using Library.Domain.Entity
@model MenuItem

<h2>Create New Menu Item</h2>

<form asp-controller="MenuItem" asp-action="Create" method="post">
    <div class="form-group">
        <label>Name:</label>
        <input asp-for="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label>Description:</label>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-group">
        <label>Url:</label>
        <input asp-for="Url" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

<p>
    <a asp-controller="MenuItem" asp-action="Index">Back to List</a>
</p>

Library/Views/MenuItem/Delete.cshtml
@using Library.Domain.Entity
@model MenuItem


<h2>Delete Menu Item</h2>

<table>
    <tr>
        <td>Title:</td>
        <td>@Model.Title</td>
    </tr>
    <tr>
        <td>Description:</td>
        <td>@Model.Description</td>
    </tr>
</table>

<p>Are you sure you want to delete this menu item?</p>

<form asp-controller="MenuItem" asp-action="Delete" method="post">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Delete</button> |
    <a asp-controller="MenuItem" asp-action="Index">Cancel</a>
</form>

Library/Views/MenuItem/Edit.cshtml
@using Library.Domain.Entity
@model MenuItem

<h2>Edit Menu Item</h2>

<form asp-controller="MenuItem" asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label>Name:</label>
        <input asp-for="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label>Description:</label>
        <input asp-for="Description" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<p>
    <a asp-controller="MenuItem" asp-action="Index">Back to List</a>
</p>

Library/Views/MenuItem/Index.cshtml
@using Library.Domain.Entity
@model List<MenuItem>


<h2>Menu Items</h2>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Url</th>
            <th>Description</th>
            <th>isActive</th>
            <th>CreatedAt</th>
            <th>ModifiedAt</th>
            <th>DeletedAt</th>
            <th>isDelete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Title</td>
                <td>@item.Url</td>
                <td>@item.Description</td>
                <td>@item.isActive</td>
                <td>@item.CreatedAt</td>
                <td>@item.ModifiedAt</td>
                <td>@item.DeletedAt</td>
                <td>@item.isDelete</td>
                <td>
                    <a asp-controller="MenuItem" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
                <td>
                    <a asp-controller="MenuItem" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<p>
    <a asp-controller="MenuItem" asp-action="Create">Create New</a>
</p>