Library/Controllers/PublisherController.cs
using Library.DAL.Interfaces;
using Library.Domain.Entity;
using Library.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class PublisherController : Controller
    {
        private readonly IPublisherRepository _publisherRepository;

        public PublisherController(IPublisherRepository publisherRepository)
        {
            _publisherRepository = publisherRepository;
        }
        public async Task<IActionResult> Index()
        {
            var publisher = await _publisherRepository.GetAllPublishers();
            return View(publisher);
        }
        public IActionResult Details(int id)
        {
            var publisher = _publisherRepository.GetPublisherById(id);
            if(publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Publisher publisher)
        {
            if(ModelState.IsValid)
            {
                publisher.CreatedBy = "";
                publisher.CreatedAt = DateTime.Now;
                publisher.ModifiedBy = "";
                publisher.ModifiedAt = DateTime.Now;
                publisher.isDelete = false;
                publisher.AddressId = 1;
                await _publisherRepository.Create(publisher);
                return RedirectToAction("Index");
            }
            return View(publisher);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var publisher = await _publisherRepository.GetPublisherById(id);
            if(publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Publisher publisher)
        {
            if(ModelState.IsValid)
            {
                publisher.CreatedBy = "";
                publisher.CreatedAt = DateTime.Now;
                publisher.ModifiedBy = "";
                publisher.ModifiedAt = DateTime.Now;
                publisher.isDelete = false;
                publisher.AddressId = 1;
                await _publisherRepository.Update(publisher);
                return RedirectToAction("Index");
            }
            return View(publisher);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var publisher = await _publisherRepository.GetPublisherById(id);
            if(publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Publisher publisher)
        {
            await _publisherRepository.Delete(publisher);
            return RedirectToAction("Index");
        }
    }
}

Library/Views/Publisher/Create.cshtml
@using Library.Domain.Entity
@model Publisher

<h2>Create Publisher</h2>

<form asp-controller="Publisher" asp-action="Create" method="post">
    <div class="form-group">
        <label>Name:</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label>Contacts:</label>
        <input asp-for="ContactInfo" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

<p>
    <a asp-controller="Publisher" asp-action="Index">Back to List</a>
</p>

Library/Views/Publisher/Delete.cshtml
@using Library.Domain.Entity
@model Publisher


<h2>Delete Publisher</h2>

<table>
    <tr>
        <td>Name:</td>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <td>Contacts:</td>
        <td>@Model.ContactInfo</td>
    </tr>
</table>

<p>Are you sure you want to delete this Publisher?</p>

<form asp-controller="Publisher" asp-action="Delete" method="post">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Delete</button> |
    <a asp-controller="Publisher" asp-action="Index">Cancel</a>
</form>

Library/Views/Publisher/Edit.cshtml
@using Library.Domain.Entity
@model Publisher

<h2>Edit Publisher</h2>

<form asp-controller="Publisher" asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label>Name:</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label>Contacts:</label>
        <input asp-for="ContactInfo" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<p>
    <a asp-controller="Publisher" asp-action="Index">Back to List</a>
</p>

Library/Views/Publisher/Index.cshtml
@using Library.Domain.Entity
@model List<Publisher>

<h2>Publishers</h2>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Contact</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.ContactInfo</td>
                <td>
                    <a asp-controller="Publisher" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
                <td>
                    <a asp-route-id="@item.Id" data-toggle="modal" data-target="#myModal">Delete</a>

                    <!-- The Modal -->
                    <div class="modal fade" id="myModal">
                        <div class="modal-dialog">
                            <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Delete Publisher</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    Are you sure you want to delete this Publisher?
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <button asp-controller="Publisher" asp-action="Delete" asp-for="@item" method="post" type="submit" class="btn btn-danger" data-dismiss="modal">Delete</button>
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                                </div>

                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<p>
    <a asp-controller="Publisher" asp-action="Create">Create New</a>
</p>