Library/Controllers/AddressController.cs
using Library.DAL.Interfaces;
using Library.Domain.Entity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics.Metrics;

namespace Library.Controllers
{
    public class AddressController : Controller
    {
        private readonly IAddressRepository _addressRepository;
        public AddressController(IAddressRepository addressRepository)
        {
            _addressRepository = addressRepository;
        }
        public async Task<IActionResult> Index()
        {
            var address = await _addressRepository.GetAllAddresses();
            return View(address);
        }
        public async Task<IActionResult> Details(int id)
        {
            var address = await _addressRepository.GetAddressById(id);
            if (address == null)
            {
                return NotFound();
            }
            return View(address);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Address address)
        {
            if (ModelState.IsValid)
            {
                address.CreatedBy = "";
                address.CreatedAt = DateTime.Now;
                address.ModifiedBy = "";
                address.ModifiedAt = DateTime.Now;
                address.isDelete = false;
                address.Id = 1;
                address.CountryId = 1;
                await _addressRepository.Create(address);
                return RedirectToAction("Index");
            }
            return View(address);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var address = await _addressRepository.GetAddressById(id);
            if (address == null)
            {
                return NotFound();
            }
            return View(address);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Address address)
        {
            if (ModelState.IsValid)
            {
                address.Id = address.Id;
                address.CreatedAt = DateTime.Now;
                address.ModifiedAt = DateTime.Now;
                address.ModifiedBy = "";
                address.CreatedBy = "";
                address.CountryId = 1;
                await _addressRepository.Update(address);
                return RedirectToAction("Index");
            }
            return View(address);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var address = await _addressRepository.GetAddressById(id);
            if (address == null)
            {
                return NotFound();
            }
            return View(address);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Address address)
        {
            await _addressRepository.Delete(address);
            return RedirectToAction("Index");
        }
    }
}

Library/Views/Address/Create.cshtml
@using Library.Domain.Entity
@model Address

<h2>Create Adress</h2>

<form asp-controller="Address" asp-action="Create" method="post">
    <div class="form-group">
        <label>Street:</label>
        <input asp-for="Street" class="form-control" />
    </div>
    <div class="form-group">
        <label>City:</label>
        <input asp-for="City" class="form-control" />
    </div>
    <div class="form-group">
        <label>Zip Code:</label>
        <input asp-for="ZipCode" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

<p>
    <a asp-controller="Address" asp-action="Index">Back to List</a>
</p>

Library/Views/Address/Delete.cshtml
@using Library.Domain.Entity
@model Address


<h2>Delete Address</h2>

<table>
    <tr>
        <td>Street:</td>
        <td>@Model.Street</td>
    </tr>
    <tr>
        <td>City:</td>
        <td>@Model.City</td>
    </tr>
    <tr>
        <td>Zip Code:</td>
        <td>@Model.ZipCode</td>
    </tr>
</table>

<p>Are you sure you want to delete this Address?</p>

<form asp-controller="Address" asp-action="Delete" method="post">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Delete</button> |
    <a asp-controller="Address" asp-action="Index">Cancel</a>
</form>

Library/Views/Address/Edit.cshtml
@using Library.Domain.Entity
@model Address

<h2>Edit Address</h2>

<form asp-controller="Address" asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label>Street:</label>
        <input asp-for="Street" class="form-control" />
    </div>
    <div class="form-group">
        <label>City:</label>
        <input asp-for="City" class="form-control" />
    </div>
    <div class="form-group">
        <label>Zip Code:</label>
        <input asp-for="ZipCode" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<p>
    <a asp-controller="Address" asp-action="Index">Back to List</a>
</p>

Library/Views/Address/Index.cshtml
@using Library.Domain.Entity
@model List<Address>


<h2>Adresses</h2>

<table>
    <thead>
        <tr>
            <th>Street</th>
            <th>City</th>
            <th>ZipCode</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Street</td>
                <td>@item.City</td>
                <td>@item.ZipCode</td>
                <td>
                    <a asp-controller="Address" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
                <td>
                    <a asp-controller="Address" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<p>
    <a asp-controller="Address" asp-action="Create">Create New</a>
</p>